version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - "./docker/mongo:/docker-entrypoint-initdb.d"
    ports:
      - 27017:27017
