version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - "./db.json:/docker-entrypoint-initdb.d/db.json"
      - "./mongo/seed.sh:/docker-entrypoint-initdb.d/seed.sh"
    ports:
      - 27017:27017
