version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - "./docker/mongo:/docker-entrypoint-initdb.d"
    ports:
      - 27017:27017

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./env.yaml:/app/env.yaml
      - ./docker/cert:/app/docker/cert
    restart: unless-stopped
    ports:
      - 1323:1323
